spring:
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment: #配置rabbimq连接环境
            spring:
              rabbitmq:
                addresses: ${spring.rabbitmq.addresses}
                #host: xxx.xx.xxx.xxx
                username: ${spring.rabbitmq.username}
                password: ${spring.rabbitmq.password}
                virtual-host: ${spring.rabbitmq.virtual-host}
      bindings:
        retryOutput:
          destination: retry_channel_for_${spring.application.name}  #exchange名称，交换模式默认是topic
          content-type: application/json
          group: ${spring.application.name}
        retryInput:
          destination: retry_channel_for_${spring.application.name}
          content-type: application/json
          group: ${spring.application.name}